stages:
  - build
  - test

build:
  image: openjdk:11-slim
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/
  script: "./gradlew clean assemble"

test:
  image: openjdk:11-slim
  stage: test
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - build/
  script: "./gradlew test"
