stages:
  - build

build:
  image: openjdk:8-slim
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: "./gradlew clean assemble"
  artifacts:
    paths:
      - build/libs/*-all.jar

